name: Deploy to Node

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: ğŸ“Œ ë…¸ë“œ ë¹Œë“œ
        uses: actions/setup-node@v3
        with:
          node-version: '20.15'
  
      - name: ğŸ“Œ ì˜ì¡´ì„± ì¶”ê°€
        run: npm install

      - name: ğŸ“Œ zip íŒŒì¼ ìƒì„±
        run: |
          mkdir deploy-node
          cp -r src/* ./deploy-node/src
          cp ./docker-compose-node.blue.yml ./deploy-node/
          cp ./docker-compose-node.green.yml ./deploy-node/
          cp ./appspec.yml ./deploy-node/
          cp ./Dockerfile ./deploy-node/
          cp ./scripts/*.sh ./deploy-node/
          cp ./package.json ./deploy-node/
          cp ./package-lock.json ./deploy-node/
          zip -r -qq ./cicd-test-node-build.zip ./deploy-node
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
        
      - name: ğŸ“Œ S3ì— ì—…ë¡œë“œ
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            ./cicd-test-node-build.zip s3://latteve-cicd-test
      # ì¶”ê°€
      - name: Code Deploy
        run: aws deploy create-deployment --application-name node-deploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name node-deploy-group
          --s3-location bucket=latteve-cicd-test,bundleType=zip,key=cicd-test-node-build.zip